#!/bin/bash

mod() {
	awk '
	BEGIN { print "" }
	// { m= m + 1 }
	/\/\// { n= n + 1 }
	/\/\*/ { n= n + 1 }
	END   { print "Lineas = ", m, ", cant cod = ", m-n, ",cant comentarios =", n, ", porcentaje =", (m-n)/m }' pruebas
}

