#!/bin/bash

hola() {
	awk '
	BEGIN { print "Analysis of \"li\"" }
	/li/  { ++n }
	END   { print "\"li\" appears in", n, "records." }' pruebas
}
{
	awk '
	BEGIN { print "Analysis of \"Codigo\"" }
	//  { ++n }
	END   { print "\"Lineas de codigo\" appears in", n, "records." }' pruebas
}
	awk '
	BEGIN { print "Analysis of \"//\"" }
	// { m= m + 1 }
	/\/\// { n= n + 1 }
	END   { print "\"//\" appears in", m - n, "records." }' pruebas
